import { FrameworkConfig, Framework } from './types';

export const frameworkConfigs: Record<Framework, FrameworkConfig> = {
  nextjs: {
    name: 'Next.js',
    description: 'Next.js 14 + React + TypeScript',
    language: 'TypeScript',
    testing: 'Jest + React Testing Library',
    lint: 'ESLint + Prettier',
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
      test: 'jest',
      'test:watch': 'jest --watch',
    },
    structure: ['src/app', 'src/components', 'src/lib', 'src/styles', 'public', 'tests'],
    dependencies: ['next', 'react', 'react-dom'],
    devDependencies: ['@types/node', '@types/react', '@types/react-dom', 'typescript', 'eslint', 'eslint-config-next', 'jest', '@testing-library/react', '@testing-library/jest-dom', 'prettier', 'husky', 'lint-staged', '@tailwindcss/postcss', 'postcss', 'autoprefixer'],
  },
  react: {
    name: 'React (Vite)',
    description: 'React + Vite + TypeScript',
    language: 'TypeScript',
    testing: 'Vitest + React Testing Library',
    lint: 'ESLint + Prettier',
    scripts: { dev: 'vite', build: 'tsc && vite build', preview: 'vite preview', test: 'vitest', 'test:watch': 'vitest --watch', lint: 'eslint .', format: 'prettier --write .' },
    structure: ['src/components', 'src/hooks', 'src/pages', 'src/services', 'src/types', 'public', 'tests'],
    dependencies: ['react', 'react-dom', 'react-router-dom'],
    devDependencies: ['@types/react', '@types/react-dom', 'typescript', 'vite', '@vitejs/plugin-react', 'eslint', '@typescript-eslint/eslint-plugin', 'prettier', 'vitest', '@testing-library/react', 'jsdom'],
  },
  vue: {
    name: 'Vue.js',
    description: 'Vue 3 + Vite + TypeScript',
    language: 'TypeScript',
    testing: 'Vitest + Vue Test Utils',
    lint: 'ESLint + Prettier',
    scripts: { dev: 'vite', build: 'vue-tsc && vite build', preview: 'vite preview', test: 'vitest', 'test:watch': 'vitest --watch', lint: 'eslint .', format: 'prettier --write .' },
    structure: ['src/components', 'src/composables', 'src/views', 'src/services', 'src/types', 'public', 'tests'],
    dependencies: ['vue', 'vue-router', 'pinia'],
    devDependencies: ['@vitejs/plugin-vue', '@vitejs/plugin-vue-jsx', 'typescript', 'vite', 'vitest', '@vue/test-utils', 'eslint', 'prettier'],
  },
  angular: {
    name: 'Angular',
    description: 'Angular 17+ + TypeScript',
    language: 'TypeScript',
    testing: 'Jasmine + Karma',
    lint: 'ESLint',
    scripts: { start: 'ng serve', build: 'ng build', test: 'ng test', 'test:watch': 'ng test --watch', lint: 'ng lint' },
    structure: ['src/app', 'src/components', 'src/services', 'src/models', 'src/assets'],
    dependencies: ['@angular/core', '@angular/common', '@angular/router'],
    devDependencies: ['@angular/cli', '@angular-devkit/build-angular', 'typescript', 'jasmine', 'karma'],
  },
  express: {
    name: 'Express/Node',
    description: 'Express + TypeScript',
    language: 'TypeScript',
    testing: 'Jest + Supertest',
    lint: 'ESLint + Prettier',
    scripts: { dev: 'ts-node-dev --respawn src/index.ts', build: 'tsc', start: 'node dist/index.js', test: 'jest', 'test:watch': 'jest --watch', lint: 'eslint .', format: 'prettier --write .' },
    structure: ['src/controllers', 'src/routes', 'src/services', 'src/types', 'src/middlewares', 'src/utils', 'tests'],
    dependencies: ['express', 'cors', 'dotenv', 'helmet'],
    devDependencies: ['@types/node', '@types/express', '@types/cors', 'typescript', 'ts-node-dev', 'jest', '@types/jest', 'supertest', '@types/supertest', 'eslint', '@typescript-eslint/eslint-plugin', '@typescript-eslint/parser', 'prettier'],
  },
  fastapi: {
    name: 'FastAPI/Python',
    description: 'FastAPI + Python 3.11',
    language: 'Python',
    testing: 'Pytest',
    lint: 'flake8 + Black + mypy',
    scripts: { dev: 'uvicorn main:app --reload', build: 'python -m compileall .', test: 'pytest', 'test:watch': 'pytest -v --tb=short -s', lint: 'flake8 .', format: 'black .' },
    structure: ['app/api', 'app/models', 'app/schemas', 'app/services', 'app/utils', 'tests'],
    dependencies: ['fastapi', 'uvicorn', 'pydantic', 'sqlalchemy'],
    devDependencies: ['pytest', 'pytest-asyncio', 'black', 'flake8', 'mypy'],
  },
  flutter: {
    name: 'Flutter',
    description: 'Flutter 3.x + Dart',
    language: 'Dart',
    testing: 'flutter_test + mocktail',
    lint: 'flutter analyze + dart format',
    scripts: { run: 'flutter run', test: 'flutter test', 'test:watch': 'flutter test --verbose', build: 'flutter build', analyze: 'flutter analyze', format: 'dart format .' },
    structure: ['lib/src', 'lib/src/screens', 'lib/src/widgets', 'lib/src/services', 'lib/src/models', 'test'],
    dependencies: ['flutter', 'provider', 'http'],
    devDependencies: ['flutter_test', 'mocktail', 'flutter_lints'],
  },
  'react-native': {
    name: 'React Native',
    description: 'React Native + Expo + TypeScript',
    language: 'TypeScript',
    testing: 'Jest',
    lint: 'ESLint + Prettier',
    scripts: { start: 'expo start', android: 'expo start --android', ios: 'expo start --ios', web: 'expo start --web', test: 'jest', 'test:watch': 'jest --watch', lint: 'eslint .', format: 'prettier --write .' },
    structure: ['src/components', 'src/screens', 'src/services', 'src/hooks', 'src/types', 'src/navigation', '__tests__'],
    dependencies: ['react', 'react-native', '@react-navigation/native', 'expo'],
    devDependencies: ['@types/react', '@types/react-native', 'typescript', 'jest', '@testing-library/react-native', 'eslint', 'prettier', 'expo-cli'],
  },
  'ionic-angular': {
    name: 'Ionic Angular',
    description: 'Ionic + Angular + Capacitor',
    language: 'TypeScript',
    testing: 'Jasmine + Karma',
    lint: 'ESLint',
    scripts: { start: 'ng serve', build: 'ng build', test: 'ng test', 'test:watch': 'ng test --watch', lint: 'ng lint', cap: 'npx cap sync' },
    structure: ['src/app', 'src/components', 'src/services', 'src/pages', 'src/models', 'src/assets'],
    dependencies: ['@ionic/angular', '@ionic/angular-toolkit', '@capacitor/core', '@capacitor/android'],
    devDependencies: ['@angular/cli', '@angular-devkit/build-angular', 'typescript', 'jasmine', 'karma'],
  },
  'ionic-react': {
    name: 'Ionic React',
    description: 'Ionic + React + Capacitor',
    language: 'TypeScript',
    testing: 'Vitest + Testing Library',
    lint: 'ESLint + Prettier',
    scripts: { dev: 'vite', build: 'tsc && vite build', test: 'vitest', 'test:watch': 'vitest --watch', lint: 'eslint .', format: 'prettier --write .', cap: 'npx cap sync' },
    structure: ['src/components', 'src/pages', 'src/services', 'src/hooks', 'src/types', 'public'],
    dependencies: ['react', 'react-dom', 'react-router-dom', '@ionic/react', '@capacitor/core'],
    devDependencies: ['@types/react', '@types/react-dom', 'typescript', 'vite', 'vitest', '@testing-library/react', 'eslint', 'prettier'],
  },
  'ionic-vue': {
    name: 'Ionic Vue',
    description: 'Ionic + Vue 3 + Capacitor',
    language: 'TypeScript',
    testing: 'Vitest + Vue Test Utils',
    lint: 'ESLint + Prettier',
    scripts: { dev: 'vite', build: 'vue-tsc && vite build', test: 'vitest', 'test:watch': 'vitest --watch', lint: 'eslint .', format: 'prettier --write .', cap: 'npx cap sync' },
    structure: ['src/components', 'src/views', 'src/services', 'src/composables', 'src/types', 'public'],
    dependencies: ['vue', 'vue-router', '@ionic/vue', '@capacitor/core'],
    devDependencies: ['@vitejs/plugin-vue', 'typescript', 'vite', 'vitest', '@vue/test-utils', 'eslint', 'prettier'],
  },
};

export function getFrameworkConfig(framework: Framework): FrameworkConfig {
  return frameworkConfigs[framework];
}
